### ISSUE TITLE
so many errors

### ISSUE THREAD

**Issue by NorthernBlow** [raghulkrishna/deepcool-ak620-digital-linux#11]
OS: Arch linux
dependencies: i tried with python-hid and python-hidapi

with python-hidapi it's throw many errors like

```journalctl
Nov 21 08:29:17 MaschinenGewehr151 python[91051]: Traceback (most recent call last):
Nov 21 08:29:17 MaschinenGewehr151 python[91051]:   File "/usr/bin/deepcool-ak-series-digital.py", line 7, in <module>
Nov 21 08:29:17 MaschinenGewehr151 python[91051]:     PRODUCT_ID = deepcool-ak-620-digital-linux
Nov 21 08:29:17 MaschinenGewehr151 python[91051]:                  ^^^^^^^^
Nov 21 08:29:17 MaschinenGewehr151 python[91051]: NameError: name 'deepcool' is not defined
Nov 21 08:29:17 MaschinenGewehr151 systemd[1]: deepcool-ak-series-digital.service: Main process exited, code=exited, 
```
after fixes that, throws another:

```journalctl
Nov 21 08:30:57 MaschinenGewehr151 python[91381]: Traceback (most recent call last):
Nov 21 08:30:57 MaschinenGewehr151 python[91381]:   File "/usr/bin/deepcool-ak-series-digital.py", line 75, in <module>
Nov 21 08:30:57 MaschinenGewehr151 python[91381]:     h.open(VENDOR_ID, PRODUCT_ID)
Nov 21 08:30:57 MaschinenGewehr151 python[91381]:   File "hidraw.pyx", line 111, in hid.device.open
Nov 21 08:30:57 MaschinenGewehr151 python[91381]: TypeError: an integer is required
Nov 21 08:30:57 MaschinenGewehr151 systemd[1]: deepcool-ak-series-digital.service: Main process exited, code=exited,
```

also, with python-hid same story but another errors like hid.device() has't arguments divice, did you mean Device?

and after fixed that, it's throws another error....

**Comment by NorthernBlow** [comment]
also, i tried to launch directly in python virtualenv and same happens.

**Comment by marcosins** [comment]
> Nov 21 08:29:17 MaschinenGewehr151 python[91051]:     PRODUCT_ID = deepcool-ak-620-digital-linux

If you're editing the python file directly, you need to specify the ID in hex. See `setup.sh`
```bash
PRODUCTS=(
    [ak620]="0x0002"
    [ak500s]="0x0004"
)
```

Here's my python file for my ak620

```python
import time

import hid
import psutil

VENDOR_ID = 0x3633  # DeepCool's Vendor ID
PRODUCT_ID = 0x0002 # ak620
SENSOR = "k10temp" # Depends on your CPU
SHOW_TEMP = True
SHOW_UTIL = False
INTERVAL = 1 # Seconds
(...)
```

Edit: The `hid` package should be provided by your distro (recommended) or installed by you, in Ubuntu 24.04 is called `python3-hid`
