### ISSUE TITLE
Equivalent software for the AK400 Digital

### ISSUE THREAD

**Issue by brunodantas** [raghulkrishna/deepcool-ak620-digital-linux#2]
I would like to know if it's possible to make this compatible with the AK400, any idea?

**Comment by brunodantas** [comment]
I checked my product ID and updated accordingly, but it didn't work:

```
VENDOR_ID = 0x3633  # DeepCool's Vendor ID
PRODUCT_ID = 0x0001  # AK400's Product ID
```

Any ideas? Also what are the exact versions of hid and psutil I should be using?

**Comment by Em2see** [comment]
> I checked my product ID and updated accordingly, but it didn't work:
> 
> ```
> VENDOR_ID = 0x3633  # DeepCool's Vendor ID
> PRODUCT_ID = 0x0001  # AK400's Product ID
> ```
> 
> Any ideas? Also what are the exact versions of hid and psutil I should be using?

you need to install hidapi
```
sudo apt-get install python-dev libusb-1.0-0-dev libudev-dev
sudo pip install hidapi==0.14.0
```

psutil
```
sudo pip install psutil==5.9.8
```

Could you please describe what errors you see ?

Also you need to check if you you have "nct6687" sensors

`python3 -c "import psutil; print(psutil.sensors_temperatures().keys())"`

**Comment by brunodantas** [comment]
Ok, installed hidapi with those commands.
Running `bash ./setup.sh` I get some output but nothing happens:

```
Created symlink /etc/systemd/system/default.target.wants/deepcool-ak620-digital.service → /lib/systemd/system/deepcool-ak620-digital.service.
Created symlink /etc/systemd/system/suspend.target.wants/deepcool-ak620-digital-restart.service → /lib/systemd/system/deepcool-ak620-digital-restart.service.
```

If I run the script manually I get these errors 
```
$ python3 deepcool-ak620-digital.py 
Traceback (most recent call last):
  File "/home/bwdm/deepcool-ak620-digital-linux-main/deepcool-ak620-digital.py", line 3, in <module>
    import hid
  File "/home/bwdm/.local/lib/python3.10/site-packages/hid/__init__.py", line 31, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
```

And this is my sensor output:

```
$ python3 -c "import psutil; print(psutil.sensors_temperatures().keys())"
dict_keys(['nvme', 'amdgpu', 'k10temp'])

```

**Comment by Algorithm0** [comment]
> > I checked my product ID and updated accordingly, but it didn't work:
> > 
> > ```
> > VENDOR_ID = 0x3633  # DeepCool's Vendor ID
> > PRODUCT_ID = 0x0001  # AK400's Product ID
> > ```
> > 
> > Any ideas? Also what are the exact versions of hid and psutil I should be using?
> 
> you need to install hidapi
> ```
> sudo apt-get install python-dev libusb-1.0-0-dev libudev-dev
> sudo pip install hidapi==0.14.0
> ```
> 
> psutil
> ```
> sudo pip install psutil==5.9.8
> ```
> 
> Could you please describe what errors you see ?
> 
> Also you need to check if you you have "nct6687" sensors
> 
> `python3 -c "import psutil; print(psutil.sensors_temperatures().keys())"`

Hey! Can you tell us how your device works with this code? I would like to add it to my project, but as I understand it, you can only see the temperature display and CPU usage. i.e. The data is displayed exclusively on the left side of the device. Does the visual display of the processor load (squares on the number) work at the same time? What happens on the right side, which is responsible for the GPU? Is everything just displayed by zeros?

**Comment by raghulkrishna** [comment]
@Algorithm0  as far as i tested it can only show temperature and usage  , the values in display TEMP and USAGE are fixed i tried to manipuate it but seems like a fixed value

**Comment by raghulkrishna** [comment]
> Ok, installed hidapi with those commands. Running `bash ./setup.sh` I get some output but nothing happens:
> 
> ```
> Created symlink /etc/systemd/system/default.target.wants/deepcool-ak620-digital.service → /lib/systemd/system/deepcool-ak620-digital.service.
> Created symlink /etc/systemd/system/suspend.target.wants/deepcool-ak620-digital-restart.service → /lib/systemd/system/deepcool-ak620-digital-restart.service.
> ```
> 
> If I run the script manually I get these errors
> 
> ```
> $ python3 deepcool-ak620-digital.py 
> Traceback (most recent call last):
>   File "/home/bwdm/deepcool-ak620-digital-linux-main/deepcool-ak620-digital.py", line 3, in <module>
>     import hid
>   File "/home/bwdm/.local/lib/python3.10/site-packages/hid/__init__.py", line 31, in <module>
>     raise ImportError(error)
> ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
> ```
> 
> And this is my sensor output:
> 
> ```
> $ python3 -c "import psutil; print(psutil.sensors_temperatures().keys())"
> dict_keys(['nvme', 'amdgpu', 'k10temp'])
> ```

I will try this next week in linux mint iso and let you know the steps
